### ISSUE TITLE
Wrong calendar day appears!

### ISSUE THREAD

**Issue by MahmoudAbunaji** [aminography/PrimeCalendar#2]
Hello , 

I'm using your great calendar 👍  in my business and i'm developing my app using Both of Hijri and Greg. calendars, 
But look like i'm phasing an issue with the current day appears in the calendar same as suppose today Hijri date is 
7 Safar and the day is Thursday but in calendar is appears as today is 6 Safar as green colored cell , Please support if there is any idea to pull 1 day back in the calendar settings , Appreciated.

Your calendar : 

![Screen Shot 2020-09-24 at 4 45 36 PM](https://user-images.githubusercontent.com/24670225/94153393-65306f80-fe85-11ea-91d2-e3b225d60910.png)

Islamic calendar :

![Screen Shot 1442-02-07 at 4 47 28 PM](https://user-images.githubusercontent.com/24670225/94153616-a9237480-fe85-11ea-98b0-9ac1655bfc1a.png)

**Comment by aminography** [comment]
Hi @MahmoudAbunaji,
Thank you for your support.
You are right. It's a known issue in the Hijri calendar that it may differ in various countries because of their longitudes. I will add the possibility to shift calendar dates.

**Comment by EsmaeelNabilM** [comment]
did you solve this issue ?

**Comment by EsmaeelNabilM** [comment]
is there any way to solve this issue yet ??

**Comment by MahmoudAbunaji** [comment]
I have cstomized and add alot of features to the calendar library tell me what do you need exactly to share with you the customized code.

**Comment by MahmoudAbunaji** [comment]
@EsmaeelNabilM 

I have cstomized and add alot of features to the calendar library tell me what do you need exactly to share with you the customized code.

**Comment by EsmaeelNabilM** [comment]
Thanks Man!
i have this same issue of the day shifting , the picker shows 19 but it's actually 20

**Comment by MahmoudAbunaji** [comment]
Can you please share your any chat account whatsapp or telegram to talk more yo my email in my profile.

**Comment by EsmaeelNabilM** [comment]
i have sent you a connection request at Linkedin

**Comment by aminography** [comment]
Hi all!
You can now shift Hijri dates using `HijriCalendar.dateAdjustingOffset` field. It is a static variable, so it configures (affects) all instances of `HijriCalendar`. By default, the value is 1, so it shifts all Hijri dates by 1 day to solve the related issue in ThreeTenBP library (like [this](https://github.com/JakeWharton/ThreeTenABP/issues/118)).
It is required to set `dateAdjustingOffset` before instantiating calendars, _e.g._ for an android app it could be in the application class:
```kotlin
class MyApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        HijriCalendar.dateAdjustingOffset = // whatever value
    }
}
```

Please update your dependencies to the versions below to have the applied fix.

```gradle
dependencies {
    implementation 'com.aminography:primedatepicker:3.6.0'
    implementation 'com.aminography:primecalendar:1.7.0'
}
```

BR/
