### ISSUE TITLE
Custom fonts?

### ISSUE THREAD

**Issue by uzman** [aminography/PrimeCalendar#5]
How to set custom fonts for all elements (day, weekday name, month name)?

**Comment by aminography** [comment]
Hi @uzman,
I guess this issue is related to the [PrimeDatePicker](https://github.com/aminography/PrimeDatePicker) repository. Anyway, you can create a `ThemeFactory` and pass it to the `applyTheme` function in the builder mechanism, like the following snippet:

```kotlin
val themeFactory = object : LightThemeFactory() {

    override val typefacePath: String?
        get() = "fonts/Righteous-Regular.ttf" // location of the font file inside the assets directory
}

val datePicker = PrimeDatePicker.bottomSheetWith(today)
        .pickSingleDay(callback)
        .applyTheme(themeFactory)
        .build()
```

**Comment by uzman** [comment]
I am using PrimeCalendarView control in layout file. It is full screen in vertical mode.
xml layout:

    <com.aminography.primedatepicker.calendarview.PrimeCalendarView
        android:id="@+id/calendar_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:dividerInsetLeft="20dp"
        app:dividerInsetRight="20dp"
        app:monthLabelTextColor="@color/textcolor"
        app:weekLabelTextColor="@color/textcolor"
        app:todayLabelTextColor="@color/textcolor"
        app:weekLabelTextSize="12sp"
        app:monthLabelTextSize="16sp"
        app:dayLabelTextSize="14sp"
        app:weekLabelBottomPadding="10dp"
        app:monthLabelBottomPadding="10dp"
        app:elementPaddingBottom="44dp"
        app:dayLabelVerticalPadding="10dp"
        app:dividerColor="#E6E7E9"
        app:flingOrientation="vertical"
        app:pickedDayBackgroundShapeType="roundSquare"
        />


here is the java codes:

        CalendarType calendarType = CalendarType.CIVIL;
        calendarView.setCalendarType(calendarType);
        calendarView.setPickType(PickType.SINGLE);
        calendarView.setMinDateCalendar(minDate);
        calendarView.setMaxDateCalendar(maxDate);
        calendarView.goTo(minDate, false);
        calendarView.setFlingOrientation(PrimeCalendarView.FlingOrientation.VERTICAL);
        calendarView.setFirstDayOfWeek(Calendar.MONDAY);
        calendarView.setWeekLabelFormatter(primeCalendar -> primeCalendar.getWeekDayNameShort().toUpperCase());
        calendarView.setOnDayPickedListener(this);

but I can not set the theme. I couldn't find the method for applying theme.
Can you help?

**Comment by aminography** [comment]
Definitely, you can set a typeface like the following:

```java
Typeface typeface = Typeface.createFromAsset(context.getAssets(), "fonts/Righteous-Regular.ttf");
calendarView.setTypeface(typeface);
```
