### ISSUE TITLE
Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.

### ISSUE THREAD

**Issue by ayoubdevv** [aminography/PrimeCalendar#6]
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.aminography:primecalendar:1.2.15.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by FarhamHosseini** [comment]
> 
> 
> Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> 
> > Could not resolve all files for configuration ':app:debugCompileClasspath'.
> > Could not find com.aminography:primecalendar:1.2.15.
> > Required by:
> > project :app
> 
> Possible solution:
> 
>     * Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Hello sir,

Use [PrimeCalendar](https://github.com/FarhamHosseini/PrimeCalendar) from my account, I been rewritten just to be included in `mavenCentral()`

Sincerely

**Comment by aminography** [comment]
Hi all.
There was a problem with my domain that took a long time to solve. Fortunately, it is available now, so I've just published the library on MavenCentral.

```
dependencies {
    implementation 'com.aminography:primecalendar:1.7.0'
}
```

Sorry for that!
BR.
